M48
; DRILL file {KiCad (6.0.0)} date Sat Jun 18 15:13:52 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-18T15:13:52-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.700
%
G90
G05
T1
X136.0Y-107.11
X136.0Y-112.89
T2
X131.1Y-97.0
X131.1Y-123.0
X132.9Y-97.0
X132.9Y-123.0
T0
M30
